<h1><center>Homework 1 - HackerRank Practice</center></h1> 
<center><img src="img/Sap_Hack_Pyt2.JPG" alt="Drawing" style="width: 300px;"/></center>

##### **Author:** Daniel Mauricio Jiménez Gutiérrez
##### **Date:** 2020/10/24
##### **Subject:** Algorithmic Methods of Data Mining
##### **Data Science Master's programme**
##### **La Sapienza University of Rome**
_____

<div style="text-align: justify "> The code below contains the development of a sort of points related to practising <b>Python</b> from the basics to the use of Numpy and some extra programming issues. Each chunk of problems has its link and a <b>number/description</b> to easily identify them.</div>

# Problem 1

In the following cells, you can find the solution to each one of the challenges proposed in the first problem.

## Introduction
(all – total: 7 - max points: 75)
https://www.hackerrank.com/domains/python/py-introduction

### 1. Say Hello, World! With Python

In [256]:
expression = "Hello, World!"
print expression

Hello, World!


### 2. Python If-Else
I looked at the answer to this exercise to figure out how to code and run the answers

In [21]:
# Provide the number
n = int(input())
# Check if the number is odd
if n % 2 != 0:
    print("Weird")
# Check if the number is even and in the inclusive range of 2 to 5, print Not Weird
elif n % 2 == 0 and n >= 2 and n <= 5:
    print("Not Weird")
# Check if the number is even and in the inclusive range of 6 to 20, print Not Weird
elif n % 2 == 0 and n >= 6 and n <= 20:
    print("Weird")
# Check if the number is even and in the inclusive range of 6 to 20, print Not Weird
elif n % 2 == 0 and n > 20:
    print("Not Weird")
else:
    print("Wrong number")

 2


Not Weird


### 3. Arithmetic Operators

In [23]:
# Provide the numbers
a = int(input())
b = int(input())

# Sum numbers
print(a + b)

# Substract numbers
print(a - b)

# Multiply numbers
print(a * b)

 4
 5


9
-1
20


### 4. Python: Division

In [25]:
# Provide the numbers
a = int(input())
b = int(input())

# Calculate divisions
print(a // b)
print(a / b)

 1
 2


0
0.5


### 5. Loops

In [28]:
# Provide the number
n = int(input())

# Execute loop
i = 0
while i < n:
    print(i ** 2)
    i += 1

 5


0
1
4
9
16


### 6. Write a function

In [33]:
# Define function
def is_leap(year):
    leap = False
    # Evaluate the conditions for leap year
    if (year % 4) == 0:
        if (year % 100) == 0:
            if (year % 400) == 0:
                leap = True
            else:
                leap = False
        else:
            leap = True
    else:
        leap = False
    # Evaluate the conditions for leap year
    return leap


# Provide the number
year = int(input())

# Return solution
print(is_leap(year))

 2000


True


### 7. Print Function

In [38]:
# Provide the number
n = int(input())

# Iterate to print sequence
for i in range(n):
    print(i + 1, end="")

 5


12345

## Data types
 (all – total: 6 - max points: 60)
https://www.hackerrank.com/domains/python/py-basic-data-types

### 1. List Comprehensions

In [3]:
# Provide the numbers
x = int(input())
y = int(input())
z = int(input())
n = int(input())

# Create all the posible combinations
combinations = [
    [i, j, k]
    for i in range(x + 1)
    for j in range(y + 1)
    for k in range(z + 1)
    if (i + j + k != n)
]
print(combinations)

 1
 1
 1
 2


[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


### 2. Find the Runner-Up Score!

In [7]:
### Provide the numbers
n = int(input())
arr = list(map(int, input().split()))

# Remove duplicates
arr = list(dict.fromkeys(arr))

# Sort the list
arr.sort()

# Print second largest element
print(arr[-2])

 5
 1 2 3 3 4


3


### 3. Nested Lists

In [ ]:
### Provide the numbers
names = []
scores = []
for i in range(int(input())):
    name = input()
    score = float(input())
    names.append(name)
    scores.append(score)
# Remove duplicates
srt_scores = list(dict.fromkeys(scores))

# Sort the list of scores
srt_scores = sorted(srt_scores, reverse=True)

# Define second lowest score
second_largest = srt_scores[-2]

# Find position of second lowest score
pos = []
for i in range(len(scores)):
    if scores[i] == second_largest:
        pos.append(i)
# Find names of positions of the second lowest score
nam_low = []
for i in pos:
    nam_low.append(names[i])
# Sort the list of names
nam_low = sorted(nam_low)

# Print name of positions of the second lowest score
for i in nam_low:
    print(i)

### 4. Finding the percentage

In [45]:
### Provide the information
n = int(input())
student_marks = {}

# Loop over students
for i in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    student_marks[name] = scores
query_name = input()

### Find average of desired student
avg = round(sum(student_marks[query_name]) / 3, 2)
print("%.2f" % avg)

 3
 Krishna 67 68 69
 Arjun 70 98 63
 Malika 52 56 60
 Malika


56.0


### 5. Lists

In [ ]:
# Provide the number
N = int(input())

final_value = []
for i in range(N):
    # Provide functions and parameters to be applied
    func = input().split()
    command = func[0]
    params = func[1:]
    # Decide if the function is or not print
    if command != "print":
        eval("final_value." + command + "(" + ",".join(params) + ")")
    else:
        print(final_value)

### 6. Tuples

In [60]:
# Provide the number and list of numbers
n = int(input())
integer_list = map(int, input().split())

# Create tuple
tuple_n = tuple(integer_list)

# Print hash
print(hash(tuple_n))

 2
 1 2


3713081631934410656


## Strings
 (all – total: 14 - max points: 220)
https://www.hackerrank.com/domains/python/py-strings ---- 
https://www.hackerrank.com/domains/python/py-strings/2

### 1. sWAP cASE

In [2]:
# Define function to swap case
def swap_case(s):
    return s.swapcase()


# Provide the string
s = input()

# Apply function
result = swap_case(s)

# Print swapped string
print(result)

 HeLlOw


hElLoW


### 2. String Split and Join

In [3]:
# Define function
def split_and_join(line):
    # write your code here
    line = line.split(" ")
    line = "-".join(line)
    return line


# Provide the string
line = input()

# Apply function
result = split_and_join(line)

# Print splitted string
print(result)

 this is a string


this-is-a-string


### 3. What's Your Name?

In [5]:
# Define function
def print_full_name(a, b):
    print("Hello ", a, " ", b, "! You just delved into python.", sep="")


# Provide the strings
first_name = input()
last_name = input()

# Apply function
print_full_name(first_name, last_name)

 a
 b


Hello a b! You just delved into python.


### 4. Mutations

In [6]:
# Define function
def mutate_string(string, position, character):
    return string[:position] + character + string[(position + 1) :]


# Provide the strings
s = input()
i, c = input().split()

# Apply function
s_new = mutate_string(s, int(i), c)

# Print result
print(s_new)

 cara
 2 k


caka


### 5. Find a string

In [7]:
# Define function
def count_substring(string, sub_string):
    # Iterate over positions
    cont = 0
    for i in range(len(string) - len(sub_string) + 1):
        # Check if sub_string in string
        if string[i : i + len(sub_string)] == sub_string:
            cont += 1
    return cont


# Provide the strings
string = input().strip()
sub_string = input().strip()

# Apply function
count = count_substring(string, sub_string)

# Print result
print(count)

 caraca
 ca


2


### 6. String Validators

In [10]:
# Provide string
s = input()

# Check if string has any alphanumeric characters
print(any([i.isalnum() for i in s]))
# Check if string has any alphabetical characters
print(any([i.isalpha() for i in s]))
# Check if string has any digits
print(any([i.isdigit() for i in s]))
# Check if string has any lowercase characters
print(any([i.islower() for i in s]))
# Check if string has any uppercase characters
print(any([i.isupper() for i in s]))

 Awa


True
True
False
True
True


### 7. Text Alignment

In [11]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input())  # This must be an odd number
c = "H"

# Top Cone
for i in range(thickness):
    print((c * i).rjust(thickness - 1) + c + (c * i).ljust(thickness - 1))
# Top Pillars
for i in range(thickness + 1):
    print((c * thickness).center(thickness * 2) + (c * thickness).center(thickness * 6))
# Middle Belt
for i in range((thickness + 1) // 2):
    print((c * thickness * 5).center(thickness * 6))
# Bottom Pillars
for i in range(thickness + 1):
    print((c * thickness).center(thickness * 2) + (c * thickness).center(thickness * 6))
# Bottom Cone
for i in range(thickness):
    print(
        (
            (c * (thickness - i - 1)).rjust(thickness)
            + c
            + (c * (thickness - i - 1)).ljust(thickness)
        ).rjust(thickness * 6)
    )

 5


    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


### 8. Text Wrap

In [12]:
# Import library
import textwrap

# Define function
def wrap(string, max_width):
    text_wr = textwrap.fill(string, max_width)
    return text_wr


# Provide the strings
string, max_width = input(), int(input())

# Apply function
result = wrap(string, max_width)

# Print result
print(result)

 abcdefgh
 2


ab
cd
ef
gh


### 9. Designer Door Mat
I looked at the answer to this exercise to figure out how to create the bottom part of the mat, because after many trials I was getting the wrong figure

In [19]:
# Provide dimensions strings
height, base = map(int, input().split())

# Loop to create the top part of the mat
for i in range(1, height, 2):
    print("".join([".|."] * i).center(base, "-"))
# Print welcome with the dimension provided
print("WELCOME".center(base, "-"))

# Loop to create the bottom part of the mat
for i in range(height - 2, -1, -2):
    print("".join([".|."] * i).center(base, "-"))

 9 27


------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


### 10. String Formatting

In [25]:
# Define function
def print_formatted(number):
    # Get the higher number of characters of the number (binary)
    nchar = len(bin(number)[2:])
    # Loop to print sequence
    for i in range(number):
        # Transform each number
        decimal = str(i + 1)
        octal = oct(i + 1)[2:]
        hexadecimal = hex(i + 1)[2:].upper()
        binary = bin(i + 1)[2:]
        # Print in desired format
        print(
            decimal.rjust(nchar),
            octal.rjust(nchar),
            hexadecimal.rjust(nchar),
            binary.rjust(nchar),
        )


# Provide the number
n = int(input())

# Apply function

 5


  1   1   1   1
  2   2   2  10
  3   3   3  11
  4   4   4 100
  5   5   5 101


### 11. Alphabet Rangoli

In [32]:
# Import library
import string

# Define function
def print_rangoli(size):
    # Bring letters of the alphabet
    letters = string.ascii_lowercase
    mat = []
    for i in range(0, size):
        # Create each line
        line = "-".join(letters[i:size])
        # Append all the lines created in the format desired
        mat.append((line[::-1] + line[1:]).center(4 * size - 3, "-"))
    # Print result
    print("\n".join(mat[:0:-1] + mat))


# Provide the number
n = int(input())

# Apply function
print_rangoli(n)

 5


--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


### 12. Capitalize!

In [49]:
# Define function
def solve(s):
    # Lop for words
    for i in s.split():
        # Capitalize each word
        s = s.replace(i, i.capitalize())
    return s


# Provide the string
s = input()

# Apply function
result = solve(s)

# Print result
print(result)

 ab bA bb 3G


Ab Ba Bb 3g


### 13. The Minion Game
I look at a part of the solution to this problem because I couldn't understand very well the directions

In [64]:
# Define function
def minion_game(string):
    # Number of characters of string
    nchar = len(string)
    # Define posible vowels
    vowels = "AEIOUaeiou"

    pts_kevin = 0
    pts_stuart = 0
    # Loop in string
    for i in range(nchar):
        # Check if vowel in word and give points to kevin
        if string[i] in vowels:
            pts_kevin += nchar - i
        # IOC Give points to kevin
        else:
            pts_stuart += nchar - i
    # Define winner
    if pts_kevin > pts_stuart:
        print("Kevin " + str(pts_kevin))
    elif pts_kevin < pts_stuart:
        print("Stuart " + str(pts_stuart))
    else:
        print("Draw")


# Provide the string
s = input()

# Apply function
minion_game(s)

 banana


Stuart 12


### 14. Merge the Tools!

In [72]:
# Import library
from collections import OrderedDict

# Define function
def merge_the_tools(string, k):
    # Get number of characters of string
    nchar = len(string)
    # Loop in string by k
    for i in range(0, nchar, k):
        # Removing duplicates and extracting subsequence
        print("".join(OrderedDict.fromkeys(string[i : i + k])))


# Provide the string
string, k = input(), int(input())

# Apply function
merge_the_tools(string, k)

 AAAAAAABBBBBC
 2


A
A
A
AB
B
B
C


## Sets
 (all – total: 13 - max points: 170)
https://www.hackerrank.com/domains/python/py-sets ****
https://www.hackerrank.com/domains/python/py-sets/2

### Introduction to Sets

In [73]:
# Define function
def average(array):
    set_arr = set(array)
    mean = sum(set_arr) / len(set_arr)
    return mean


# Provide the number and values
n = int(input())
arr = list(map(int, input().split()))

# Apply function
result = average(arr)

# Print result
print(result)

 3
 1 1 2


1.5


### 2. Symmetric Difference

In [88]:
# Provide the numbers
n1, M = input(), set(input().split())
n2, N = input(), set(input().split())

# Calculate symmetric difference
result = M.symmetric_difference(N)

# Convert to int
result = list(map(int, result))

# Sort result
result = sorted(result)

# Print result
for i in result:
    print(i)

 1
 1 2 3 4
 1
 3 4


1
2


### 3. No Idea!

In [ ]:
# Provide the numbers
n = input()
array = input().split()
A = set(input().split())
B = set(input().split())

# Loop over array values
happiness = 0
for i in array:
    # Check if sum to hapiness
    if i in A:
        happiness += 1
    # Check if susbtract to hapiness
    if i in B:
        happiness -= 1
# Print result
print(happiness)

### 4. Set .add()

In [95]:
# Provide the numbers
n = int(input())
country_set = set()

# Loop to provide the numbers
for i in range(n):
    country = input()
    country_set.add(country)
# Print result
print(len(country_set))

 3
 cas
 perro
 cas


2


### 5. Set .discard(), .remove() & .pop()

In [96]:
# Provide the number and set
n = int(input())
s = set(map(int, input().split()))

# Loop to get functions
for i in range(int(input())):
    func = input().split()
    command = func[0]
    params = func[1:]
    # Decide if the function is or not pop
    if command != "pop":
        eval("s." + command + "(" + ",".join(params) + ")")
    else:
        s.pop()
# Imprimir resultado
print(sum(s))

 9
 1 2 3 4 5 6 7 8 9
 10
 pop
 remove 9
 discard 9
 discard 8
 remove 7
 pop
 discard 6
 remove 5
 pop
 discard 5


4


### 6. Set .union() Operation

In [1]:
# Provide the numbers and sets
n = int(input())
n_roll = set(input().split())
b = int(input())
b_roll = set(input().split())

# Print result
print(len(n_roll.union(b_roll)))

 9
 1 2 3 4 5 6 7 8 9
 5
 1 2 3 4


9


### 7. Set .intersection() Operation

In [2]:
# Provide the numbers and sets
n = int(input())
n_roll = set(input().split())
b = int(input())
b_roll = set(input().split())

# Print result
print(len(n_roll.intersection(b_roll)))

 9
 1 2 3 4 5
 9
 1 2 3


3


### 8. Set .difference() Operation

In [3]:
# Provide the numbers and sets
n = int(input())
n_roll = set(input().split())
b = int(input())
b_roll = set(input().split())

# Print result
print(len(n_roll.difference(b_roll)))

 9
 1 2 3 4 5
 9
 1 2 3


2


### 9. Set .symmetric_difference() Operation

In [ ]:
# Provide the numbers and sets
n = int(input())
n_roll = set(input().split())
b = int(input())
b_roll = set(input().split())

# Print result
print(len(n_roll.symmetric_difference(b_roll)))

### 10. Set Mutations

In [6]:
# Provide the number and set
n_A = int(input())
A = set(map(int, input().split()))

# Loop to get functions
for i in range(int(input())):
    func = input().split()
    command = func[0]
    set2 = set(map(int, input().split()))
    eval("A." + command + "(set2)")
# Imprimir resultado
print(sum(A))

 16
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
 4
 intersection_update 10
 2 3 5 6 8 9 1 4 7 11
 update 2
 55 66
 symmetric_difference_update 5
 22 7 35 62 58
 difference_update 7
 11 22 35 55 58 62 66


38


### 11. The Captain's Room

I looked at the answer to this exercise

In [8]:
# Provide the number
k = input()

# Loop over rooms
set1 = set()
set2 = set()
for i in input().split():
    if i not in set1:
        set1.add(i)
    else:
        set2.add(i)
set1.difference_update(set2)
# Print result
print(set1.pop())

 5
 1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 


8


### 12. Check Subset

In [13]:
# Loop over tests
n = int(input())
for i in range(n):
    # Provide numbers and sets
    n_A = input()
    A = set(map(int, input().split()))
    n_B = input()
    B = set(map(int, input().split()))

    # Return result
    print(A.issubset(B))

 1
 1 2 3
 4
 1 2 3 4
 5


False


### 13. Check Strict Superset

In [14]:
# Provide the number
A = set(input().split())
cont = 0
n = int(input())
# Loop over number
for i in range(n):
    # Provide the sets
    sets = set(input().split())
    # Check if is superset
    if A.issuperset(sets):
        cont += 1
# Print result
print(cont == n)

 1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
 2
 1 2 3 4 5
 100 11 12


False


## Collections
(all – total: 8 - max points: 220)
https://www.hackerrank.com/domains/python/py-collections

### 1. collections.Counter()

In [2]:
# Import library
import collections

# Provide the numbers and list
X = int(input())
shoe_sizes = collections.Counter(map(int, input().split()))
N = int(input())

# Loop over customers
money = 0
for i in range(N):
    size, price = map(int, input().split())
    # Check if available shoes
    if shoe_sizes[size]:
        money += price
        shoe_sizes[size] -= 1
# Print result
print(money)

 2
 1 2 3 3 2 1
 2
 1 3
 2 6


9


### 2. DefaultDict Tutorial

In [3]:
# Import library
import collections

# Provide the numbers and dictionary
n, m = map(int, input().split())
dicc = collections.defaultdict(list)

# Loop over group A
for i in range(1, n + 1):
    dicc[input()].append(str(i))
# Loop over group B
for i in range(m):
    print(" ".join(dicc[input()]) or -1)

 5 2
 a
 a
 b
 a
 b
 a


1 2 4


 a


1 2 4


### 3. Collections.namedtuple()

In [5]:
# Import library
import collections

# Provide the number and colum names
N = int(input())
columns = ",".join(input().split())
students_tp = collections.namedtuple("students_tp", columns)

# Loop over students
sum = 0
for i in range(N):
    row = input().split()
    # Store row of each student
    student = students_tp(*row)
    sum += int(student.MARKS)
# Print result
print(sum / N)

 5
 ID         MARKS      NAME       CLASS     
 1          97         Raymond    7         
 2          50         Steven     4         
 3          91         Adrian     9         
 4          72         Stewart    5         
 5          80         Peter      6 


78.0


### 4. Collections.OrderedDict()

In [7]:
# Import library
import collections

# Generate dictionary
dicc = collections.OrderedDict()
N = int(input())

# Loop over items
for i in range(N):
    item, price = input().rsplit(" ", 1)
    dicc[item] = dicc.get(item, 0) + int(price)
# Print result
[print(i, dicc[i]) for i in dicc]

 9
 BANANA FRIES 12
 POTATO CHIPS 30
 APPLE JUICE 10
 CANDY 5
 APPLE JUICE 10
 CANDY 5
 CANDY 5
 CANDY 5
 POTATO CHIPS 30


BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


[None, None, None, None]

### 5. Word Order

In [9]:
# Import library
import collections

# Provide the number
n = int(input())
dicc = collections.OrderedDict()

# Loop over numbers
for i in range(n):
    word = input()
    # Check if word exists previously
    if word in dicc:
        dicc[word] += 1
    else:
        dicc[word] = 1
# Print result
print(len(dicc))
for i, j in dicc.items():
    print(j, end=" ")

 4
 hola
 lao
 oloh
 hola


3
2 1 1 

### 6. collections.deque()

In [10]:
# Import library
import collections

# Provide the number and set
N = int(input())
s = collections.deque()

# Loop to get functions
for i in range(N):
    func = input().split()
    command = func[0]
    params = func[1:]
    # Decide if the function is or not pop
    if command != "pop":
        eval("s." + command + "(" + ",".join(params) + ")")
    else:
        s.pop()
# Imprimir resultado
print(*s)

 6
 append 1
 append 2
 append 3
 appendleft 4
 pop
 popleft


1 2


### 7. Piling Up!
I looked at the discussion forum in this exercise because I couldn't understand correctly the directions.

In [12]:
# Import library
import collections

# Provide the number
T = int(input())

# Loop over tests
for i in range(T):
    k, n = input(), collections.deque(map(int, input().split()))
    result = True

    # Loop over tests
    for j in range(len(n) - 1):
        if n[0] >= n[1]:
            n.popleft()
        elif n[-1] >= n[-2]:
            n.pop()
        else:
            result = False
            break
    # Print result
    if result:
        print("Yes")
    else:
        print("No")

 2
 6
 4 3 2 1 3 4


Yes


 3
 1 3 2


No


### 8. Company Logo

In [14]:
# Import libraries
import math
import os
import random
import re
import sys
import collections

# Provide the string
s = input().strip()
s = sorted(s)

# Get count and most common
count = collections.Counter(s).most_common()

# Sort
count = sorted(count, key=lambda x: (x[1] * -1, x[0]))

# Print result
for i in range(0, 3):
    print(count[i][0], count[i][1])

 aabbbccde


b 3
a 2
c 2


## Date and Time
 (all – total: 2 - max points: 40)
https://www.hackerrank.com/domains/python/py-date-time

### 1. Calendar Module

In [20]:
# Import library
import calendar

# Provide the date
mm, dd, yy = map(int, input().split())

# Print result
result = calendar.day_name[calendar.weekday(yy, mm, dd)].upper()
print(result)

 08 05 2015


WEDNESDAY


### 2. Time Delta

In [19]:
# Import libraries
import math
import os
import random
import re
import sys
import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    # Establish date format
    format_time = "%a %d %b %Y %H:%M:%S %z"
    # Provide the dates
    t1 = datetime.datetime.strptime(t1, format_time)
    t2 = datetime.datetime.strptime(t2, format_time)
    # Calculate delta
    result = str(int(abs((t1 - t2).total_seconds())))
    return result


# Provide the number
T = int(input())

# Loop over dates
for i in range(T):
    t1 = input()
    t2 = input()

    # Apply function
    delta = time_delta(t1, t2)

    # Print result
    print(result)

 2
 Sun 10 May 2015 13:54:36 -0700
 Sun 10 May 2015 13:54:36 -0000


False


 Sat 02 May 2015 19:54:36 +0530
 Fri 01 May 2015 13:54:36 -0000


False


## Exceptions
 (only 1 - max points: 10)
https://www.hackerrank.com/challenges/exceptions

In [22]:
# Provide the number
T = int(input())

# Loop over cases
for i in range(T):
    a, b = input().split()

    # Check if there is an error
    try:
        print(int(a) // int(b))
    except BaseException as err:
        print("Error Code:", err)

 3
 1 0


Error Code: integer division or modulo by zero


 2 $


Error Code: invalid literal for int() with base 10: '$'


 3 1


3


## Built-ins
 (only 3 - max points: 80)
https://www.hackerrank.com/challenges/zipped  ---- 
https://www.hackerrank.com/challenges/python-sort-sort  ---- 
https://www.hackerrank.com/challenges/ginorts

### 1. Zipped!
This program runs well in Hackerranks, but here there is an error I could not understand why happened

In [49]:
# Provide the numbers
N, X = map(int, input().split())

# Loop over students marks
all_marks = list()
for i in range(X):
    marks = map(float, input().split())
    # Append marks
    all_marks.append(marks)
# Print result
for i in zip(*all_marks):
    print(sum(i) / len(i))

 5 3
 89 90 78 93 80
 90 91 85 88 86
 91 92 83 89 90.5


### 2. Athlete Sort
 I looked at the solution of this problem to know how to begin

In [50]:
# Impot libraries
import math
import os
import random
import re
import sys

# Provide the numbers
nm = input().split()
n = int(nm[0])
m = int(nm[1])
arr = []

# Loop over athletes
for i in range(n):
    arr.append(list(map(int, input().rstrip().split())))
# Provide the numbers
k = int(input())

arr.sort(key=lambda x: x[k])

# Print result
for line in arr:
    print(*line, sep=" ")

 5 3
 10 2 5
 7 1 0
 9 9 9
 1 23 12
 6 5 9
 1


7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


### 3. ginortS

In [55]:
# Loop over string
lower = []
upper = []
odd = []
even = []
for i in sorted(input()):
    # Check if char is alphanumeric
    if i.isalpha():
        # Check if char is uppercase
        if i.isupper():
            aux = upper
        else:
            aux = lower
    else:
        if int(i) % 2:
            aux = odd
        else:
            aux = even
    aux.append(i)
print("".join(lower + upper + odd + even))

 Sorting1234


ginortS1324


## Python Functionals
 (only 1 - max points: 20)
https://www.hackerrank.com/challenges/map-and-lambda-expression

In [66]:
# Create cube function with lambda
cube = lambda x: x ** 3

# Define fibonacci function
def fibonacci(n):
    x1 = 0
    x2 = 1
    # Loop over number
    for i in range(n):
        # Keep the value of a even outside function
        yield x1
        # Calculate sums with previous values
        x1, x2 = x2, x1 + x2


# Provide the number
n = int(input())

# Print result
print(list(map(cube, fibonacci(n))))

 5


[0, 1, 1, 8, 27]


## Regex and Parsing challenges
 (all – total: 17 - max points: 560)
https://www.hackerrank.com/domains/python/py-regex ----
https://www.hackerrank.com/domains/python/py-regex/2

### 1. Detect Floating Point Number

I looked at the answer of this exercise

In [247]:
# Import library
import re

# Provide the string
N = int(input())

# Loop over number
for i in range(N):
    s = input()

    # Print result
    regex_pattern = r"^[-+]?[0-9]*\.[0-9]+$"
    result = bool(re.match(regex_pattern, s))
    print(result)

 4
 4.0O0


False


 -1.00


True


 +4.54


True


 SomeRandomStuff


False


### 2. Re.split()

In [27]:
# Import library
import re

# Define pattern
regex_pattern = r"[,.]+"
s = input()

# Print result
result = "\n".join(re.split(regex_pattern, s))
print(result)

 100,000,000.00


100
000
000
00


### 3. Group(), Groups() & Groupdict()

In [306]:
# Import library
import re

# Define pattern
regex_pattern = r"([a-zA-Z0-9])\1"
s = input()
found = re.search(regex_pattern, s)

# Print result
if found:
    print(found.group(1))
else:
    print(-1)

 1..0011


0


### 4. Re.findall() & Re.finditer()

In [29]:
# Import library
import re

# Define pattern
regex_pattern = r"(?<=[qwrtypsdfghjklzxcvbnm])([aeiou]{2,})(?=[qwrtypsdfghjklzxcvbnm])"
s = input().strip()
found = re.findall(regex_pattern, s, re.IGNORECASE)

# Print result
if found:
    for i in found:
        print(i)
else:
    print(-1)

 rabcdeefgyYhFjkIoomnpOeorteeeeet


ee
Ioo
Oeo
eeeee


### 5. Re.start() & Re.end()

In this exercise I checked the answer of Hackerranks

In [31]:
# Import library
import re

# Provide the strings
s = input()
k = input()
sub = re.compile(k)
found = sub.search(s)

# Find patterns recursively
if found:
    while found:
        print("({}, {})".format(found.start(), found.end() - 1))
        found = sub.search(s, found.start() + 1)
else:
    print("(-1, -1)")

 asdsassaa
 aa


(7, 8)


### 6. Regex Substitution

In [32]:
# Import library
import re

# Provide the number
N = int(input())

# Loop over lines
for i in range(N):
    # Provide the string
    s = input()

    # Define pattern
    regex_pattern1 = r"(?<= )(&&)(?= )"
    regex_pattern2 = r"(?<= )(\|\|)(?= )"
    s = re.sub(regex_pattern1, "and", s)
    s = re.sub(regex_pattern2, "or", s)

    # Print result
    print(s)

 1
 a && 1 & 2  || 3 ||


a and 1 & 2  or 3 ||


### 7. Validating Roman Numerals 

In [35]:
# Import library
import re

# Define pattern
regex_pattern = r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"

# Print result
print(str(bool(re.match(regex_pattern, input()))))

 MMMCCCDXI


False


### 8. Validating phone numbers

In [38]:
# Import library
import re

# Provide the number
N = int(input())

# Loop over number
for i in range(N):
    # Define pattern
    regex_pattern = r"[789]\d{9}$"

    # Print result
    if re.match(regex_pattern, input()):
        print("YES")
    else:
        print("NO")

 1
 999999999


NO


### 9. Validating and Parsing Email Addresses

In [43]:
# Import library
import re

# Provide the number
n = int(input())

# Loop over number
for i in range(n):
    # Provide the strings
    name, email = input().split(" ")

    # Define pattern
    regex_pattern = r"<[A-Za-z](\w|-|\.|_)+@[A-Za-z]+\.[A-Za-z]{1,3}>"
    found = re.match(regex_pattern, email)

    # Print result
    if found:
        print(name, email)

 1
 DEXTER <dexter@hotmail.com>


DEXTER <dexter@hotmail.com>


### 10. Hex Color Code

I look at the answer of this exercise to know to avoid words like #BED

In [14]:
# Import library
import re

# Provide the number
N = int(input())

# Loop over number
for i in range(N):

    # Define pattern
    regex_pattern = r":?.(#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{3})"
    found = re.findall(regex_pattern, input())

    # Print result
    if found:
        print(*found, sep="\n")

 1
 #BED


### 11. HTML Parser - Part 1

In [12]:
# Import library
from html.parser import HTMLParser

# Define class
class MyHTMLParser(HTMLParser):
    # Define functions
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        for attr in attrs:
            print("->", " > ".join(map(str, attr)))

    def handle_endtag(self, tag):
        print("End   :", tag)

    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        for attr in attrs:
            print("->", " > ".join(map(str, attr)))


# Define the number
N = int(input())

# Loop over number of lines
html_code = []
for i in range(N):
    html_code.append(input().strip())
html_code = "".join(html_code)

# Call class
parser = MyHTMLParser()

# Apply functions inside class
parser.feed(html_code)

 2
 <body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
 <html><head><title>HTML Parser - I</title></head>


Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html
Start : html
Start : head
Start : title
End   : title
End   : head


### 12. HTML Parser - Part 2

In [6]:
# Import library
from html.parser import HTMLParser

# Define class
class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        # Define functions
        if "\n" in data:
            print(">>> Multi-line Comment")
            print(data)
        else:
            print(">>> Single-line Comment")
            print(data)

    def handle_data(self, data):
        if data != "\n":
            print(">>> Data")
            print(data)


# Loop over number of lines
html = ""
for i in range(int(input())):
    html += input().rstrip()
    html += "\n"
# Call class
parser = MyHTMLParser()

# Apply functions inside class
parser.feed(html)

 4
 <!--[if IE 9]>IE9-specific content
 <![endif]-->
 <div> Welcome to HackerRank</div>
 <!--[if IE 9]>IE9-specific content<![endif]-->


>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


### 13. Detect HTML Tags, Attributes and Attribute Values

In [17]:
# Import library
from html.parser import HTMLParser

# Define class
class MyHTMLParser(HTMLParser):
    # Define functions
    def handle_starttag(self, tag, attrs):
        print(tag)
        for attr in attrs:
            print("->", " > ".join(attr))


# Provide the number
N = int(input())

# Loop over number of lines
html_code = []
for i in range(N):
    html_code.append(input().strip())
html_code = "".join(html_code)

# Call class
parser = MyHTMLParser()

# Apply functions inside class
parser.feed(html_code)

 9
 <head>
 <title>HTML</title>
 </head>
 <object type="application/x-flash" 
   data="your-file.swf" 
   width="0" height="0">
   <!-- <param name="movie" value="your-file.swf" /> -->
   <param name="quality" value="high"/>
 </object>


head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


### 14. Validating UID

In [35]:
# Import library
import re

# Provide the number
T = int(input())

# Loop over number
for i in range(T):
    s = input().strip()

    # Define pattern for 2 uppercase
    regex_pattern = r".*([A-Z].*){2,}"
    upper = bool(re.match(regex_pattern, s))

    # Define pattern for 3 digits
    regex_pattern = r".*([0-9].*){3,}"
    digit = bool(re.match(regex_pattern, s))

    # Define pattern for alphanumeric characters
    regex_pattern = r"([A-Za-z0-9]){10}$"
    alphanum = bool(re.match(regex_pattern, s))

    # Define pattern for repeating characters
    regex_pattern = r".*(.).*\1"
    repeat = bool(re.match(regex_pattern, s))

    # Print result
    if upper and digit and alphanum and not repeat:
        print("Valid")
    else:
        print("Invalid")

 1
 1234568


Invalid


### 15. Validating Credit Card Numbers

In [34]:
# Import library
import re

# Provide the number
T = int(input())

# Loop over number
for i in range(T):
    s = input().strip()

    # Define pattern of a credit card sequence (not including the repetition of numbers)
    regex_pattern = r"^([456][0-9]{3})(-?)([0-9]{4})(-?)([0-9]{4})(-?)([0-9]{4})$"
    whole_credit_c = bool(re.match(regex_pattern, s))

    # Define pattern of repeating more that 4 consecutive numbers
    regex_pattern = r"([0-9])\1{3,}"
    repeat = bool(re.search(regex_pattern, s.replace("-", "")))

    # Print result
    if whole_credit_c and not repeat:
        print("Valid")
    else:
        print("Invalid")

 1
 5133-3367-8912-3456


Invalid


### 16. Validating Postal Codes

In [36]:
# Define pattern of number between 100000 and 999999
regex_integer_in_range = r"^[1-9][0-9]{5}$"
# Define pattern of alternate repeating number
regex_alternating_repetitive_digit_pair = r"([0-9])(?=[0-9]\1)"

# Import library
import re

# Provide the number
P = input()

# Print result
print(
    bool(re.match(regex_integer_in_range, P))
    and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2
)

 110000


False


### 17. Matrix Script

In [68]:
# Import libraries
import math
import os
import random
import re
import sys


# Provide the numbers
first_multiple_input = input().rstrip().split()
n = int(first_multiple_input[0])
m = int(first_multiple_input[1])

# Loop over rows
matrix = []
for _ in range(n):
    matrix_item = list(input())
    matrix.append(matrix_item)
# Transpose to get values as rows where needed
matrix = list(map(list, zip(*matrix)))

# Loop over matrix rows (previously the columns)
text = ""
for i in range(m):
    text += "".join(matrix[i])
# Define pattern
regex_pattern = r"(?<=[A-Za-z0-9])([^A-Za-z0-9]+)(?=[A-Za-z0-9])"
s = re.sub(regex_pattern, " ", text)

# Print result
print(s)

 2 2 
 1 2
 3 4


1324


## XML
 (all – total: 2 - max points: 40)
https://www.hackerrank.com/domains/python/xml

### 1. XML 1 - Find the Score

In [ ]:
# Import libraries
import sys
import xml.etree.ElementTree as etree

# Define function
def get_attr_number(node):
    score = sum(len(child.attrib) for child in node.iter())
    return score


# Provide the number
sys.stdin.readline()

# Provide the xml
xml = sys.stdin.read()
tree = etree.ElementTree(etree.fromstring(xml))
root = tree.getroot()

# Apply function
print(get_attr_number(root))

### 2. XML2 - Find the Maximum Depth

I looked at the answer to this exercise because I'm NOT very related to recursion.

In [7]:
# Import library
import xml.etree.ElementTree as etree

# Define function
maxdepth = 0


def depth(elem, level):
    global maxdepth
    if level == maxdepth:
        maxdepth += 1
    for child in elem:
        depth(child, level + 1)


n = int(input())
xml = ""
for i in range(n):
    xml = xml + input() + "\n"
tree = etree.ElementTree(etree.fromstring(xml))
depth(tree.getroot(), -1)

# Print result
print(maxdepth)

 6
 <feed xml:lang='en'>
     <title>HackerRank</title>
     <subtitle lang='en'>Programming challenges</subtitle>
     <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
     <updated>2013-12-25T12:00:00</updated>
 </feed>


1


## Closures and Decorations 
 (all – total: 2 - max points: 60)
https://www.hackerrank.com/domains/python/closures-and-decorators

### 1. Standardize Mobile Number Using Decorators

In [2]:
# Define function
def wrapper(f):
    def fun(l):
        # complete the function
        f("+91 " + i[-10:-5] + " " + i[-5:] for i in l)

    return fun


# Activate wrapper
@wrapper

# Define function
def sort_phone(l):
    print(*sorted(l), sep="\n")


# Provide the numbers
l = [input() for _ in range(int(input()))]

# Apply function
sort_phone(l)

 3
 07895462130
 919875641230
 9195969878


+91 78954 62130
+91 91959 69878
+91 98756 41230


### 2. Decorators 2 - Name Directory

In [5]:
# Import library
import operator

# Define function
def person_lister(f):
    def inner(people):
        # complete the function
        return map(f, sorted(people, key=lambda x: float(x[2])))

    return inner


# Activate person_lister
@person_lister
def name_format(person):
    return ("Mr. " if (person[3] == "M") else "Ms. ") + person[0] + " " + person[1]


# Provide the people
people = [input().split() for i in range(int(input()))]

# Print result
print(*name_format(people), sep="\n")

 3
 Mike Thomson 20 M
 Robert Bustle 32 M
 Andria Bustle 30 F


Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


## Numpy
 (all – total: 15 - max points: 300)
https://www.hackerrank.com/domains/python/numpy ----
https://www.hackerrank.com/domains/python/numpy/2

### 1. Arrays

In [9]:
# Import library
import numpy as np

# Define function
def arrays(arr):
    arr = np.array(arr[::-1]).astype(float)
    return arr


# Provide the number
arr = input().strip().split(" ")

# Print result
result = arrays(arr)
print(result)

 1 2 3 4 -8 -10


[-10.  -8.   4.   3.   2.   1.]


### 2. Shape and Reshape

In [11]:
# Import library
import numpy as np

# Provide the numbers
integers = np.array(input().split()).astype(int)

# Change shape
integers.shape = (3, 3)

# Print result
print(integers)

 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3. Transpose and Flatten

In [12]:
# Import library
import numpy as np

# Provide the numbers
N, M = map(int, input().split())

# Loop over numbers
matrix = []
for i in range(N):
    values = input().split()
    matrix.append(values)
# Convert to matrix
matrix = np.array(matrix).astype(int)

# Print results
print(matrix.transpose())
print(matrix.flatten())

 2 2
 1 2
 3 4


[[1 3]
 [2 4]]
[1 2 3 4]


### 4. Concatenate

In [26]:
# Import library
import numpy as np

# Provide the numbers
N, M, P = map(int, input().split())

# Loop over number N
arr1 = np.array([])
for i in range(N):
    # Provide the numbers
    aux = np.array(input().split()).astype(int)
    arr1 = np.append(arr1, aux, axis=0).astype(int)
# Loop over number M
arr2 = np.array([])
for i in range(M):
    # Provide the numbers
    aux = np.array(input().split()).astype(int)
    arr2 = np.append(arr2, aux, axis=0).astype(int)
# Reshape to desired size
arr1.shape = (N, P)
arr2.shape = (M, P)

# Print result
print(np.concatenate((arr1, arr2), axis=0))

 4 3 2
 1 2
 1 2 
 1 2
 1 2
 3 4
 3 4
 3 4


[[1. 2.]
 [1. 2.]
 [1. 2.]
 [1. 2.]
 [3. 4.]
 [3. 4.]
 [3. 4.]]


### 5. Zeros and Ones

In [42]:
# Import library
import numpy as np

# Provide the shape
arr = list(map(int, input().split()))

# Print result
print(np.zeros(arr, dtype=np.int))
print(np.ones(arr, dtype=np.int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


### 6.  Eye and Identity

I look at the answer of this exercise to figure out how to modify the print options

In [43]:
# Import library
import numpy as np

# Set printing options
np.set_printoptions(sign=" ")

# Provide the numbers
N, M = list(map(int, input().split()))
print(np.eye(N, M, k=0))

 3 3


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 7. Array Mathematics

In [57]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N, M = map(int, input().split())

# Loop over numbers
n1 = []
n2 = []
for i in range(N):
    n1.append(input().split())
for i in range(N):
    n2.append(input().split())
# Transform list to numpy array
n1 = np.array(n1, int)
n2 = np.array(n2, int)

# Print result
print(n1 + n2)
print(n1 - n2)
print(n1 * n2)
print(n1 // n2)
print(n1 % n2)
print(n1 ** n2)

 2 4
 1 2 3 4
 1 2 3 4
 5 6 7 7
 5 6 7 7


[[ 2  4  6  8]
 [10 12 14 14]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [25 36 49 49]]
[[1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]]
[[     1      4     27    256]
 [  3125  46656 823543 823543]]


### 8. Floor, Ceil and Rint

In [61]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N = np.array(input().split(), float)

# Print result
print(np.floor(N))
print(np.ceil(N))
print(np.rint(N))

 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


### 9. Sum and Prod

In [63]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N, M = map(int, input().split())

# Loop over numbers
n1 = []
for i in range(N):
    n1.append(input().split())
# Transform list to numpy array
n1 = np.array(n1, int)

# Sum over axis 0
sum_n1 = np.sum(n1, axis=0)

# Print result
print(np.prod(sum_n1))

 2 2
 1 2
 3 4


24


### 10. Min and Max

In [64]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N, M = map(int, input().split())

# Loop over numbers
n1 = []
for i in range(N):
    n1.append(input().split())
# Transform list to numpy array
n1 = np.array(n1, int)

# Minimum over axis 0
min_n1 = np.min(n1, axis=1)

# Print result
print(np.max(min_n1))

 4 2
 2 5
 3 7
 1 3
 4 0


3


### 11. Mean, Var, and Std



In [69]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N, M = map(int, input().split())

# Loop over numbers
n1 = []
for i in range(N):
    n1.append(input().split())
# Transform list to numpy array
n1 = np.array(n1, int)

# Print result
print(np.mean(n1, axis=1))
print(np.var(n1, axis=0))
print("{0:.18f}".format(np.std(n1)))

 2 2
 1 2
 3 4


[ 1.5  3.5]
[ 1.  1.]
1.118033988749894903


### 12. Dot and Cross

In [76]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N = int(input())

# Loop over numbers
A = []
for i in range(N):
    A.append(input().split())
B = []
for i in range(N):
    B.append(input().split())
# Transform list to numpy array
A = np.array(A, int)
B = np.array(B, int)

# Print result
print(np.dot(A, B))

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


### 13. Inner and Outer

In [81]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
A = np.array(input().split(), int)
B = np.array(input().split(), int)

# Print result
print(np.inner(A, B))
print(np.outer(A, B))

 0 1
 2 3


3
[[0 0]
 [2 3]]


### 14. Polynomials

In [83]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
P = np.array(input().split(), float)
x = np.array(input(), int)

# Print result
print(np.polyval(P, x))

 1.1 2 3
 0


3.0


### 15. Linear Algebra

In [86]:
# Import library
import numpy as np

np.set_printoptions(sign=" ")

# Provide the numbers
N = int(input())

# Loop over numbers
A = []
for i in range(N):
    A.append(input().split())
# Transform list to numpy array
A = np.array(A, float)

# Print result
print(np.linalg.det(A).round(2))

 2
 1.1 1.1
 1.1 1.2


0.11


# Problem 2
In the following cells, you can find the solution to each one of the challenges proposed in the second problem.

## Birthday Cake Candles
https://www.hackerrank.com/challenges/birthday-cake-candles

In [ ]:
# Import libraries
import math
import os
import random
import re
import sys

# Define function
def birthdayCakeCandles(candles):
    # Calculate maximum height
    max_h = max(candles)

    # Loop over numbers
    count = 0
    for i in candles:
        if i == max_h:
            count += 1
    # Return the value
    return count


if __name__ == "__main__":
    fptr = open(os.environ["OUTPUT_PATH"], "w")

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + "\n")

    fptr.close()

## Number Line Jumps
https://www.hackerrank.com/challenges/kangaroo

In [104]:
# Import libraries
import math
import os
import random
import re
import sys

# Define functoin
def kangaroo(x1, v1, x2, v2):
    # Solving equation to find point of convergence (point = (pos_k2-pos_k1)/(vel_k1-vel_k2))
    point = (x2 - x1) / (v1 - v2)

    # When going at the same speed and starting from the same point
    if v1 == v2 and x1 == x2:
        return "YES"
    # When going at the same speed but starting from different points
    elif v1 == v2:
        return "NO"
    # Check if position is integer to know if they converge
    if point == int(point) and point > 0:
        return "YES"
    else:
        return "NO"


if __name__ == "__main__":
    fptr = open(os.environ["OUTPUT_PATH"], "w")

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + ""\n")

    fptr.close()

 0 2 5 3


YES



## Viral Advertising
https://www.hackerrank.com/challenges/strange-advertising

In [120]:
# Import libraries
import math
import os
import random
import re
import sys

# Define funciton
def viralAdvertising(n):
    # Set initial values
    shared = 5
    liked = math.floor(shared / 2)
    cum = liked
    
    # Loop over days starting form second one
    for i in range(2,n+1):
        # Calculate shared people
        shared = math.floor(shared / 2) * 3
        
        # Calculate liked people
        liked = math.floor(shared / 2)
        
        # Calculate cumulative sum of liked people
        cum += liked
    
    return(int(cum))

if __name__ == "__main__":
    fptr = open(os.environ["OUTPUT_PATH"], "w")

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + "\n")

    fptr.close()

 5


24



## Recursive Digit Sum
https://www.hackerrank.com/challenges/recursive-digit-sum

In [179]:
# Import libraries
import math
import os
import random
import re
import sys
import itertools

# Define function for applying super digit
def apply_super_digit(P):
    # Check if P is digit
    if P <= 9 and P >= 1:
        return P
    else:
        # Calculate sum of digits
        P = sum(map(int, list(str(P))))
        # Execute the recursive function
        return apply_super_digit(P)


# Define function to call super digit
def superDigit(n, k):
    # Calculate sum of digits
    P = sum(map(int, list(str(n))))
    result = apply_super_digit(P * k)
    return result


if __name__ == "__main__":
    fptr = open(os.environ["OUTPUT_PATH"], "w")

    nk = input().split()

    n = nk[0]

    k = int(nk[1])

    result = superDigit(n, k)

    fptr.write(str(result) + "\n")

    fptr.close()

 12 1


3



## Insertion Sort - Part 1
https://www.hackerrank.com/challenges/insertionsort1

In [272]:
# Import libraries
import random
import re
import sys

# Define function
def insertionSort1(n, arr):
    # Store last position
    stored = arr[-1]

    # loop over array and check if last number is lower than each value
    i = n - 2
    while stored < arr[i] and i >= 0:
        arr[i + 1] = arr[i]
        print(" ".join(map(str, arr)))
        i -= 1
    # Change number in correct position
    arr[i + 1] = stored
    print(" ".join(map(str, arr)))


if __name__ == "__main__":
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)

 5
 2 4 6 8 3


2 4 6 8 8
2 4 6 6 8
2 4 4 6 8
2 3 4 6 8


## Insertion Sort - Part 2
https://www.hackerrank.com/challenges/insertionsort2

In [276]:
# Import libraries
import math
import os
import random
import re
import sys

# Complete the insertionSort2 function below.
def insertionSort2(n, arr):
    # Loop over all the elements of the array
    for j in range(1, n):
        # Store each position
        stored = arr[j]
        i = j - 1

        # loop over array and check if last number is lower than each value
        while stored < arr[i] and i >= 0:
            arr[i + 1] = arr[i]
            i -= 1
        # Change number in correct position
        arr[i + 1] = stored
        print(" ".join(map(str, arr)))


if __name__ == "__main__":
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)

 6
 1 4 3 5 6 2


1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
